# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hackathon_001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for hackathon_001
pod 'Cosmos'
pod 'Parse', :inhibit_warnings => true
pod 'NVActivityIndicatorView'
end
